import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>IntelHero - Competitive Intelligence Platform</title>
        <meta name="description" content="IntelHero monitors competitor websites and alerts you to changes. Welcome Scout users and join the waitlist for early access." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="IntelHero - Competitive Intelligence Platform" />
        <meta property="og:description" content="IntelHero monitors competitor websites and alerts you to changes. Welcome Scout users and join the waitlist for early access." />
        <meta property="og:image" content="/public/globe.svg" />
        <meta property="og:url" content="https://intelhero.com" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="IntelHero - Competitive Intelligence Platform" />
        <meta name="twitter:description" content="IntelHero monitors competitor websites and alerts you to changes. Welcome Scout users and join the waitlist for early access." />
        <meta name="twitter:image" content="/public/globe.svg" />
        <style>{`
          html {
            scroll-behavior: smooth;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
