import "./globals.css";
import DarkModeToggle from "./DarkModeToggle";

// import { Geist, Geist_Mono } from "next/font/google";
// Font import removed due to missing export in Next.js 15.3.3
// You may add a custom font import or use a different Google Font as needed.

const geistSans = { variable: "--font-geist-sans" };
const geistMono = { variable: "--font-geist-mono" };

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>IntelHero - Competitive Intelligence Platform</title>
        <meta name="description" content="IntelHero monitors competitor websites and alerts you to changes. Welcome Scout users and join the waitlist for early access." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="IntelHero - Competitive Intelligence Platform" />
        <meta property="og:description" content="IntelHero monitors competitor websites and alerts you to changes. Welcome Scout users and join the waitlist for early access." />
        <meta property="og:image" content="/public/globe.svg" />
        <meta property="og:url" content="https://intelhero.com" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="IntelHero - Competitive Intelligence Platform" />
        <meta name="twitter:description" content="IntelHero monitors competitor websites and alerts you to changes. Welcome Scout users and join the waitlist for early access." />
        <meta name="twitter:image" content="/public/globe.svg" />
        <style>{`
          html {
            scroll-behavior: smooth;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeToggle />
        {children}
      </body>
    </html>
  );
}
